### ISSUE TITLE
Errors for EasyImage

### ISSUE THREAD

**Issue by czerwonkabartosz** [ckeditor/ckeditor-cloudservices-core#11]
We should prepare errors for EasyImage and create base Cloud Services error in this repository.

**Comment by czerwonkabartosz** [comment]
Also, it will be cool if base error does not use `lodash` @PatrykMiszczak

**Comment by Reinmar** [comment]
Could you explain more clearly what is this ticket about?

**Comment by czerwonkabartosz** [comment]
> Could you explain more clearly what is this ticket about?

I'm not sure that is needed because all information about this we have in Cloud Services repository.
But if it's important for you, here you find a short info about this issue.

Cloud Service has dedicated errors for each services with the readable message, codes and all needed data. Additionally, base Cloud Services error has a method to generate event name which is used to emit the event with the error, so it's possible to listen to the specific error (using code). For example, Letters listen to this events.

Example:
```js
class EasyImageError extends ServiceError {
	constructor( code, message, data = {} ) {
		super( code, message, data, EasyImageError );
	}

	static createNotSupportedMimeType( mimeType ) {
		return new EasyImageError( this.CODES.NOT_SUPPORTED_FILE, 'Message', { mimeType } );
	}

	static createTooBigFile( size, maxSize ) {
		return new EasyImageError( this.CODES.TOO_BIG_FILE, `Too big file. Max size is ${maxSize}` );
	}
	
	static createFileNotFound(){
		// more
	}
	
	// more
	
	static get CODES() {
		return {
			TOO_BIG_FILE: 0,
			NOT_SUPPORTED_FILE: 1
		};
	}
	
	static get TYPE() {
		return 'EasyImageError';
	}
}

```

Becuase rest of Cloud Service libs are private, so we have to move `CSError` and `ServiceError` classes here and add dedicated errors for EI.

**Comment by czerwonkabartosz** [comment]
This issue may not be up to date ... We are talking about changes on the CS side.

**Comment by czerwonkabartosz** [comment]
We decided to move Cloud Services classes to the backend, so I close this issue.
